<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="WebForms_Routing.Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        Default page
        <br />
        <asp:Panel runat="server" ID="hardCoddedLinks" GroupingText="Hard-Codded links">
            <ul>
                <li>
                    <asp:HyperLink 
                        NavigateUrl="~/SalesReportSummary/2010" 
                        Text="Sales Report Summary"
                        runat="server" ID="hcSalesReportSummaryLink" />
                </li>
                <li>
                    <asp:HyperLink 
                        NavigateUrl="~/SalesReport/WA/2011" 
                        Text="SalesReport"
                        runat="server" ID="hcSalesReportLink" />
                </li>
                <li>
                    <asp:HyperLink 
                        NavigateUrl="~/ExpenseReport/CA/2012/Leviatans/?page=10&game=Warcraft" 
                        Text="Expenses report"
                        runat="server" ID="hcExpenseReportLink" />
                </li>
            </ul>
        </asp:Panel>
        <br />
        <asp:Panel runat="server" ID="dynamicMarkupLinks" GroupingText="Dynamic-Markup links">
            <ul>
                <li>
                    <asp:HyperLink 
                        NavigateUrl="<%$RouteUrl: year=2010 %>" 
                        Text="Sales Report Summary"
                        ID="dmSalesReportSummaryLink"
                        runat="server" />
                </li>
                <li>
                    <asp:HyperLink
                        NavigateUrl="<%$RouteUrl: locale=WA, year=2011, routeName=SalesRoute %>"
                        Text="SalesReport"
                        runat="server" ID="dmSalesReportLink" />
                </li>
                <li>
                    <asp:HyperLink
                        NavigateUrl='<%$RouteUrl: routeName=ExpensesRoute, locale=CA, year=2012, page=10, game=Warcraft %>'
                        Text="Expenses report"
                        runat="server" ID="dmExpenseReportLink" />
                </li>
            </ul>
        </asp:Panel>
        <br />
        <asp:Panel runat="server" ID="dynamicCodeLinks" GroupingText="Links generated by Code">
            <ul>
                <li>
                    <asp:HyperLink 
                        NavigateUrl="" 
                        Text="Sales Report Summary"
                        ID="salesReportSummaryLink"
                        runat="server" />
                </li>
                <li>
                    <asp:HyperLink
                        NavigateUrl=""
                        Text="SalesReport"
                        runat="server" ID="salesReportLink" />
                </li>
                <li>
                    <asp:HyperLink
                        NavigateUrl=""
                        Text="Expenses report"
                        runat="server" ID="expenseReportLink" />
                </li>
            </ul>
        </asp:Panel>
    </div>
    </form>
</body>
</html>
